// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: pluginapi/proto/plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeID) Reset() {
	*x = NodeID{}
	mi := &file_pluginapi_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeID) ProtoMessage() {}

func (x *NodeID) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeID.ProtoReflect.Descriptor instead.
func (*NodeID) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *NodeID) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *NodeID) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type NodeClaim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *NodeID                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeClaim) Reset() {
	*x = NodeClaim{}
	mi := &file_pluginapi_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeClaim) ProtoMessage() {}

func (x *NodeClaim) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeClaim.ProtoReflect.Descriptor instead.
func (*NodeClaim) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *NodeClaim) GetId() *NodeID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *NodeClaim) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type RelationClaim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	From          *NodeID                `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            *NodeID                `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,4,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationClaim) Reset() {
	*x = RelationClaim{}
	mi := &file_pluginapi_proto_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationClaim) ProtoMessage() {}

func (x *RelationClaim) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationClaim.ProtoReflect.Descriptor instead.
func (*RelationClaim) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *RelationClaim) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *RelationClaim) GetFrom() *NodeID {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *RelationClaim) GetTo() *NodeID {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *RelationClaim) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type IngestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeClaim           `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Relations     []*RelationClaim       `protobuf:"bytes,2,rep,name=relations,proto3" json:"relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestionRequest) Reset() {
	*x = IngestionRequest{}
	mi := &file_pluginapi_proto_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestionRequest) ProtoMessage() {}

func (x *IngestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestionRequest.ProtoReflect.Descriptor instead.
func (*IngestionRequest) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *IngestionRequest) GetNodes() []*NodeClaim {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *IngestionRequest) GetRelations() []*RelationClaim {
	if x != nil {
		return x.Relations
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pluginapi_proto_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_plugin_proto_rawDescGZIP(), []int{4}
}

type NameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameResponse) Reset() {
	*x = NameResponse{}
	mi := &file_pluginapi_proto_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameResponse) ProtoMessage() {}

func (x *NameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameResponse.ProtoReflect.Descriptor instead.
func (*NameResponse) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *NameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_pluginapi_proto_plugin_proto protoreflect.FileDescriptor

const file_pluginapi_proto_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1cpluginapi/proto/plugin.proto\x12\tpluginapi\"0\n" +
	"\x06NodeID\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\xb3\x01\n" +
	"\tNodeClaim\x12!\n" +
	"\x02id\x18\x01 \x01(\v2\x11.pluginapi.NodeIDR\x02id\x12D\n" +
	"\n" +
	"properties\x18\x02 \x03(\v2$.pluginapi.NodeClaim.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf6\x01\n" +
	"\rRelationClaim\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12%\n" +
	"\x04from\x18\x02 \x01(\v2\x11.pluginapi.NodeIDR\x04from\x12!\n" +
	"\x02to\x18\x03 \x01(\v2\x11.pluginapi.NodeIDR\x02to\x12H\n" +
	"\n" +
	"properties\x18\x04 \x03(\v2(.pluginapi.RelationClaim.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"v\n" +
	"\x10IngestionRequest\x12*\n" +
	"\x05nodes\x18\x01 \x03(\v2\x14.pluginapi.NodeClaimR\x05nodes\x126\n" +
	"\trelations\x18\x02 \x03(\v2\x18.pluginapi.RelationClaimR\trelations\"\a\n" +
	"\x05Empty\"\"\n" +
	"\fNameResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2|\n" +
	"\rCatalogPlugin\x121\n" +
	"\x04Name\x12\x10.pluginapi.Empty\x1a\x17.pluginapi.NameResponse\x128\n" +
	"\aCollect\x12\x10.pluginapi.Empty\x1a\x1b.pluginapi.IngestionRequestB8Z6github.com/naira-project/naira/catalog/pluginapi/protob\x06proto3"

var (
	file_pluginapi_proto_plugin_proto_rawDescOnce sync.Once
	file_pluginapi_proto_plugin_proto_rawDescData []byte
)

func file_pluginapi_proto_plugin_proto_rawDescGZIP() []byte {
	file_pluginapi_proto_plugin_proto_rawDescOnce.Do(func() {
		file_pluginapi_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pluginapi_proto_plugin_proto_rawDesc), len(file_pluginapi_proto_plugin_proto_rawDesc)))
	})
	return file_pluginapi_proto_plugin_proto_rawDescData
}

var file_pluginapi_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pluginapi_proto_plugin_proto_goTypes = []any{
	(*NodeID)(nil),           // 0: pluginapi.NodeID
	(*NodeClaim)(nil),        // 1: pluginapi.NodeClaim
	(*RelationClaim)(nil),    // 2: pluginapi.RelationClaim
	(*IngestionRequest)(nil), // 3: pluginapi.IngestionRequest
	(*Empty)(nil),            // 4: pluginapi.Empty
	(*NameResponse)(nil),     // 5: pluginapi.NameResponse
	nil,                      // 6: pluginapi.NodeClaim.PropertiesEntry
	nil,                      // 7: pluginapi.RelationClaim.PropertiesEntry
}
var file_pluginapi_proto_plugin_proto_depIdxs = []int32{
	0, // 0: pluginapi.NodeClaim.id:type_name -> pluginapi.NodeID
	6, // 1: pluginapi.NodeClaim.properties:type_name -> pluginapi.NodeClaim.PropertiesEntry
	0, // 2: pluginapi.RelationClaim.from:type_name -> pluginapi.NodeID
	0, // 3: pluginapi.RelationClaim.to:type_name -> pluginapi.NodeID
	7, // 4: pluginapi.RelationClaim.properties:type_name -> pluginapi.RelationClaim.PropertiesEntry
	1, // 5: pluginapi.IngestionRequest.nodes:type_name -> pluginapi.NodeClaim
	2, // 6: pluginapi.IngestionRequest.relations:type_name -> pluginapi.RelationClaim
	4, // 7: pluginapi.CatalogPlugin.Name:input_type -> pluginapi.Empty
	4, // 8: pluginapi.CatalogPlugin.Collect:input_type -> pluginapi.Empty
	5, // 9: pluginapi.CatalogPlugin.Name:output_type -> pluginapi.NameResponse
	3, // 10: pluginapi.CatalogPlugin.Collect:output_type -> pluginapi.IngestionRequest
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_pluginapi_proto_plugin_proto_init() }
func file_pluginapi_proto_plugin_proto_init() {
	if File_pluginapi_proto_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pluginapi_proto_plugin_proto_rawDesc), len(file_pluginapi_proto_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pluginapi_proto_plugin_proto_goTypes,
		DependencyIndexes: file_pluginapi_proto_plugin_proto_depIdxs,
		MessageInfos:      file_pluginapi_proto_plugin_proto_msgTypes,
	}.Build()
	File_pluginapi_proto_plugin_proto = out.File
	file_pluginapi_proto_plugin_proto_goTypes = nil
	file_pluginapi_proto_plugin_proto_depIdxs = nil
}
