// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: pluginapi/proto/plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatalogPlugin_Name_FullMethodName    = "/pluginapi.CatalogPlugin/Name"
	CatalogPlugin_Collect_FullMethodName = "/pluginapi.CatalogPlugin/Collect"
)

// CatalogPluginClient is the client API for CatalogPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogPluginClient interface {
	Name(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NameResponse, error)
	Collect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IngestionRequest, error)
}

type catalogPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogPluginClient(cc grpc.ClientConnInterface) CatalogPluginClient {
	return &catalogPluginClient{cc}
}

func (c *catalogPluginClient) Name(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NameResponse)
	err := c.cc.Invoke(ctx, CatalogPlugin_Name_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogPluginClient) Collect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IngestionRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestionRequest)
	err := c.cc.Invoke(ctx, CatalogPlugin_Collect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogPluginServer is the server API for CatalogPlugin service.
// All implementations must embed UnimplementedCatalogPluginServer
// for forward compatibility.
type CatalogPluginServer interface {
	Name(context.Context, *Empty) (*NameResponse, error)
	Collect(context.Context, *Empty) (*IngestionRequest, error)
	mustEmbedUnimplementedCatalogPluginServer()
}

// UnimplementedCatalogPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogPluginServer struct{}

func (UnimplementedCatalogPluginServer) Name(context.Context, *Empty) (*NameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Name not implemented")
}
func (UnimplementedCatalogPluginServer) Collect(context.Context, *Empty) (*IngestionRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method Collect not implemented")
}
func (UnimplementedCatalogPluginServer) mustEmbedUnimplementedCatalogPluginServer() {}
func (UnimplementedCatalogPluginServer) testEmbeddedByValue()                       {}

// UnsafeCatalogPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogPluginServer will
// result in compilation errors.
type UnsafeCatalogPluginServer interface {
	mustEmbedUnimplementedCatalogPluginServer()
}

func RegisterCatalogPluginServer(s grpc.ServiceRegistrar, srv CatalogPluginServer) {
	// If the following call panics, it indicates UnimplementedCatalogPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogPlugin_ServiceDesc, srv)
}

func _CatalogPlugin_Name_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogPluginServer).Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogPlugin_Name_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogPluginServer).Name(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogPlugin_Collect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogPluginServer).Collect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogPlugin_Collect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogPluginServer).Collect(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogPlugin_ServiceDesc is the grpc.ServiceDesc for CatalogPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pluginapi.CatalogPlugin",
	HandlerType: (*CatalogPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Name",
			Handler:    _CatalogPlugin_Name_Handler,
		},
		{
			MethodName: "Collect",
			Handler:    _CatalogPlugin_Collect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pluginapi/proto/plugin.proto",
}
