version: '3'

vars:
  POSTGRES_NAMESPACE: idp-system
  POSTGRES_MANIFEST: ./infra/kubernetes/postgres.yaml

tasks:
  deploy:
    internal: true
    desc: Deploy the shared PostgreSQL instance to kind
    cmds:
      - kubectl apply -f {{.POSTGRES_MANIFEST}}
      - kubectl -n {{.POSTGRES_NAMESPACE}} rollout status deploy/postgres --timeout=180s
      - kubectl -n {{.POSTGRES_NAMESPACE}} get pods

  undeploy:
    internal: true
    desc: Remove the shared PostgreSQL instance from kind
    cmds:
      - kubectl delete -f {{.POSTGRES_MANIFEST}} --ignore-not-found
