# Slim OpenMetadata dependencies for local kind development
mysql:
  primary:
    extraFlags: "--innodb-buffer-pool-size=256M --innodb-log-file-size=64M"
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 2Gi
    persistence:
      size: 5Gi

opensearch:
  opensearchJavaOpts: "-Xmx512m -Xms512m"
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
  persistence:
    size: 5Gi

airflow:
  enabled: false
