version: "2"

linters:
  default: none
  enable:
    - gocritic
    - revive
    - nolintlint
  settings:
    gocritic:
      enabled-checks:
        - ruleguard
      settings:
        ruleguard:
          rules: "rules/ruleguard.go"
    nolintlint:
      require-explanation: true
  exclusions:
    rules:
      - linters:
          - revive
        text: "should have comment"
