version: "2"

linters:
  default: none
  enable:
    - gocritic
  settings:
    gocritic:
      enabled-checks:
        - ruleguard
      settings:
        ruleguard:
          rules: "rules/ruleguard.go"
  exclusions:
    rules:
      - linters:
          - revive
        text: "should have comment"
