version: "2"

linters:
  default: none
  enable:
    - gocritic # collection of checks that detect style and performance issues
    - revive # claims to be replacement of golint
  settings:
    gocritic:
      enabled-checks:
        - ruleguard
        - paramTypeCombine
      settings:
        ruleguard:
          rules: "rules/ruleguard.go" # check if errs are wrapped
    revive:
      enable-default-rules: true
      rules:
        - name: package-comments # good candidate to enable in future to improve codebase documentation
          disabled: true
  exclusions:
    rules:
      - linters:
          - revive
        text: "should have comment"
