[alias]
goreadme = "go:github.com/posener/goreadme/cmd/goreadme"

[tools]
buf = "1.71"
go = "1.26"
"go:github.com/akavel-reply/goreadme/cmd/goreadme" = "v0.0.0-20260713150707-1c867fc238cb" # personal fork with improvements
task = "3.51"
# deploy/
helm = "4.2"
kubectl = "1.36" # update kind in kind-config.yaml if changing version 
kind = "0.32"
python = "3.11"
