[alias]
goreadme = "go:github.com/posener/goreadme/cmd/goreadme"

[tools]
buf = "1.71"
go = "1.26"
"go:github.com/akavel-reply/goreadme/cmd/goreadme" = "v0.0.0-20260713150707-1c867fc238cb" # personal fork with improvements
golangci-lint = "2.13.2"
shellcheck = "0.11"
# deploy/
helm = "4.2"
kubectl = "1.36" # update KIND_NODE_IMAGE in Tiltfile if changing version
kind = "0.32"
yq = "4" # chart render tests
helm-ct = "3" # ct lint
kubeconform = "0.8"
python = "3.11"
