{{- if .Values.catalog.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "naira.labels" . | nindent 4 }}
    {{- include "naira.selector" (dict "root" . "name" "catalog") | nindent 4 }}
{{- end }}
