apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - core/infra/kubernetes
  - llm-inference/infra/kubernetes/litellm.yaml
  - llm-inference/infra/kubernetes/postgres.yaml
  - mlops/infra/kubernetes/mlflow.yaml
  - mlops/infra/kubernetes/openmetadata-secrets.yaml
