// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugin/v1/plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeID) Reset() {
	*x = NodeID{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeID) ProtoMessage() {}

func (x *NodeID) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeID.ProtoReflect.Descriptor instead.
func (*NodeID) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *NodeID) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *NodeID) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type NodeClaim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *NodeID                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeClaim) Reset() {
	*x = NodeClaim{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeClaim) ProtoMessage() {}

func (x *NodeClaim) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeClaim.ProtoReflect.Descriptor instead.
func (*NodeClaim) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *NodeClaim) GetId() *NodeID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *NodeClaim) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type RelationClaim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	From          *NodeID                `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            *NodeID                `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,4,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationClaim) Reset() {
	*x = RelationClaim{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationClaim) ProtoMessage() {}

func (x *RelationClaim) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationClaim.ProtoReflect.Descriptor instead.
func (*RelationClaim) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *RelationClaim) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *RelationClaim) GetFrom() *NodeID {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *RelationClaim) GetTo() *NodeID {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *RelationClaim) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type CollectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeClaim           `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Relations     []*RelationClaim       `protobuf:"bytes,2,rep,name=relations,proto3" json:"relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectResponse) Reset() {
	*x = CollectResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectResponse) ProtoMessage() {}

func (x *CollectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectResponse.ProtoReflect.Descriptor instead.
func (*CollectResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *CollectResponse) GetNodes() []*NodeClaim {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *CollectResponse) GetRelations() []*RelationClaim {
	if x != nil {
		return x.Relations
	}
	return nil
}

type CollectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectRequest) Reset() {
	*x = CollectRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectRequest) ProtoMessage() {}

func (x *CollectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectRequest.ProtoReflect.Descriptor instead.
func (*CollectRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

var File_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x16plugin/v1/plugin.proto\x12\tplugin.v1\"0\n" +
	"\x06NodeID\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\xb3\x01\n" +
	"\tNodeClaim\x12!\n" +
	"\x02id\x18\x01 \x01(\v2\x11.plugin.v1.NodeIDR\x02id\x12D\n" +
	"\n" +
	"properties\x18\x02 \x03(\v2$.plugin.v1.NodeClaim.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf6\x01\n" +
	"\rRelationClaim\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12%\n" +
	"\x04from\x18\x02 \x01(\v2\x11.plugin.v1.NodeIDR\x04from\x12!\n" +
	"\x02to\x18\x03 \x01(\v2\x11.plugin.v1.NodeIDR\x02to\x12H\n" +
	"\n" +
	"properties\x18\x04 \x03(\v2(.plugin.v1.RelationClaim.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"u\n" +
	"\x0fCollectResponse\x12*\n" +
	"\x05nodes\x18\x01 \x03(\v2\x14.plugin.v1.NodeClaimR\x05nodes\x126\n" +
	"\trelations\x18\x02 \x03(\v2\x18.plugin.v1.RelationClaimR\trelations\"\x10\n" +
	"\x0eCollectRequest2X\n" +
	"\x14CatalogPluginService\x12@\n" +
	"\aCollect\x12\x19.plugin.v1.CollectRequest\x1a\x1a.plugin.v1.CollectResponseBAZ?github.com/naira-project/naira/catalog/pluginapi/proto;pluginv1b\x06proto3"

var (
	file_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_plugin_v1_plugin_proto_rawDescData []byte
)

func file_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_plugin_proto_rawDesc), len(file_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_plugin_v1_plugin_proto_rawDescData
}

var file_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_plugin_v1_plugin_proto_goTypes = []any{
	(*NodeID)(nil),          // 0: plugin.v1.NodeID
	(*NodeClaim)(nil),       // 1: plugin.v1.NodeClaim
	(*RelationClaim)(nil),   // 2: plugin.v1.RelationClaim
	(*CollectResponse)(nil), // 3: plugin.v1.CollectResponse
	(*CollectRequest)(nil),  // 4: plugin.v1.CollectRequest
	nil,                     // 5: plugin.v1.NodeClaim.PropertiesEntry
	nil,                     // 6: plugin.v1.RelationClaim.PropertiesEntry
}
var file_plugin_v1_plugin_proto_depIdxs = []int32{
	0, // 0: plugin.v1.NodeClaim.id:type_name -> plugin.v1.NodeID
	5, // 1: plugin.v1.NodeClaim.properties:type_name -> plugin.v1.NodeClaim.PropertiesEntry
	0, // 2: plugin.v1.RelationClaim.from:type_name -> plugin.v1.NodeID
	0, // 3: plugin.v1.RelationClaim.to:type_name -> plugin.v1.NodeID
	6, // 4: plugin.v1.RelationClaim.properties:type_name -> plugin.v1.RelationClaim.PropertiesEntry
	1, // 5: plugin.v1.CollectResponse.nodes:type_name -> plugin.v1.NodeClaim
	2, // 6: plugin.v1.CollectResponse.relations:type_name -> plugin.v1.RelationClaim
	4, // 7: plugin.v1.CatalogPluginService.Collect:input_type -> plugin.v1.CollectRequest
	3, // 8: plugin.v1.CatalogPluginService.Collect:output_type -> plugin.v1.CollectResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_plugin_v1_plugin_proto_init() }
func file_plugin_v1_plugin_proto_init() {
	if File_plugin_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_plugin_proto_rawDesc), len(file_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_v1_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_plugin_v1_plugin_proto = out.File
	file_plugin_v1_plugin_proto_goTypes = nil
	file_plugin_v1_plugin_proto_depIdxs = nil
}
