apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: naira
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: naira
    namespace: flux-system
  path: ./deploy/dev/stacks
  prune: true
  timeout: 2m
  wait: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: catalog
      namespace: idp-system