apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - catalog.yaml
  - litellm.yaml
  - mlflow.yaml
  - postgres.yaml
  - ui.yaml
images:
  - name: ui
    newName: ghcr.io/naira-project/naira-ui
    newTag: sha-9f5ef2b
  - name: catalog
    newName: ghcr.io/naira-project/naira-catalog
    newTag: sha-9f5ef2b
  - name: litellm
    newName: ghcr.io/naira-project/naira-plugin-litellm
    newTag: sha-9f5ef2b
  - name: mlflow
    newName: ghcr.io/naira-project/naira-plugin-mlflow
    newTag: sha-9f5ef2b
  - name: depl-calls-svc
    newName: ghcr.io/naira-project/naira-plugin-depl-calls-svc
    newTag: sha-9f5ef2b
  - name: fluxcd
    newName: ghcr.io/naira-project/naira-plugin-fluxcd
    newTag: sha-9f5ef2b