{{- if and .Values.secret.create .Values.secret.stringData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "catalog.secretName" . }}
  labels:
    {{- include "catalog.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secret.stringData | nindent 2 }}
{{- end }}
