version: '3'

tasks:
  build:
    internal: true
    cmds:
      - docker build -t {{.IMAGE}} -f {{.DIR}}/Dockerfile ../../

  load:
    internal: true
    cmds:
      - kind load docker-image {{.IMAGE}} --name {{.CLUSTER_NAME}}