# https://docs.open-metadata.org/v1.12.x/quick-start/local-kubernetes-deployment
# Create kubernetes secrets that contains MySQL and Airflow passwords as secrets.
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: openmetadata
type: Opaque
stringData:
  openmetadata-mysql-password: openmetadata_password
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  namespace: openmetadata
type: Opaque
stringData:
  openmetadata-airflow-password: admin
