apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - catalog.yaml
  - portal.yaml
  - ui.yaml
images:
  - name: ui
    newName: ghcr.io/naira-project/naira-ui
    newTag: sha-e6093a9
  - name: catalog
    newName: ghcr.io/naira-project/naira-catalog
    newTag: sha-e6093a9
  - name: litellm
    newName: ghcr.io/naira-project/naira-plugin-litellm
    newTag: sha-e6093a9
  - name: mlflow
    newName: ghcr.io/naira-project/naira-plugin-mlflow
    newTag: sha-e6093a9
  - name: depl-calls-svc
    newName: ghcr.io/naira-project/naira-plugin-depl-calls-svc
    newTag: sha-e6093a9
  - name: depl-uses-litellm
    newName: ghcr.io/naira-project/naira-plugin-depl-uses-litellm
    newTag: sha-e6093a9
  - name: fluxcd
    newName: ghcr.io/naira-project/naira-plugin-fluxcd
    newTag: sha-e6093a9
  - name: openmetadata
    newName: ghcr.io/naira-project/naira-plugin-openmetadata
    newTag: sha-e6093a9
  - name: depl-from-repo
    newName: ghcr.io/naira-project/naira-plugin-depl-from-repo
    newTag: sha-8bee2fb
  - name: github
    newName: ghcr.io/naira-project/naira-plugin-github
    newTag: sha-8bee2fb
  - name: portal
    newName: ghcr.io/naira-project/naira-portal
    newTag: sha-e6093a9