// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: plugin/v1/plugin.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatalogPluginService_Collect_FullMethodName = "/plugin.v1.CatalogPluginService/Collect"
)

// CatalogPluginServiceClient is the client API for CatalogPluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogPluginServiceClient interface {
	Collect(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*CollectResponse, error)
}

type catalogPluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogPluginServiceClient(cc grpc.ClientConnInterface) CatalogPluginServiceClient {
	return &catalogPluginServiceClient{cc}
}

func (c *catalogPluginServiceClient) Collect(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*CollectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectResponse)
	err := c.cc.Invoke(ctx, CatalogPluginService_Collect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogPluginServiceServer is the server API for CatalogPluginService service.
// All implementations must embed UnimplementedCatalogPluginServiceServer
// for forward compatibility.
type CatalogPluginServiceServer interface {
	Collect(context.Context, *CollectRequest) (*CollectResponse, error)
	mustEmbedUnimplementedCatalogPluginServiceServer()
}

// UnimplementedCatalogPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogPluginServiceServer struct{}

func (UnimplementedCatalogPluginServiceServer) Collect(context.Context, *CollectRequest) (*CollectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Collect not implemented")
}
func (UnimplementedCatalogPluginServiceServer) mustEmbedUnimplementedCatalogPluginServiceServer() {}
func (UnimplementedCatalogPluginServiceServer) testEmbeddedByValue()                              {}

// UnsafeCatalogPluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogPluginServiceServer will
// result in compilation errors.
type UnsafeCatalogPluginServiceServer interface {
	mustEmbedUnimplementedCatalogPluginServiceServer()
}

func RegisterCatalogPluginServiceServer(s grpc.ServiceRegistrar, srv CatalogPluginServiceServer) {
	// If the following call panics, it indicates UnimplementedCatalogPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogPluginService_ServiceDesc, srv)
}

func _CatalogPluginService_Collect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogPluginServiceServer).Collect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogPluginService_Collect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogPluginServiceServer).Collect(ctx, req.(*CollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogPluginService_ServiceDesc is the grpc.ServiceDesc for CatalogPluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogPluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.v1.CatalogPluginService",
	HandlerType: (*CatalogPluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Collect",
			Handler:    _CatalogPluginService_Collect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin/v1/plugin.proto",
}
