server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /v1/ {
        proxy_pass http://catalog.idp-system.svc.cluster.local:8090;
    }

    location /content-configuration.json {
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, OPTIONS";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
